FROM python:3
MAINTAINER raccoony <raccoonyy@gmail.com>

RUN apt-get update && apt-get -y install libpq-dev python-dev
RUN apt-get update && apt-get -y install --no-install-recommends apt-utils

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# ...put your own build instructions here...
RUN apt-get update && apt-get upgrade -y -o Dpkg::Options::="--force-confold"

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

ADD ./requirements.txt /app/
RUN pip install -r /app/requirements.txt

ADD ./manage.py /app/
ADD ./compose/django/start-dev.sh /app/start-dev.sh
RUN chmod +x /app/*.sh

ENTRYPOINT ["sh","/app/start-dev.sh"]

ENV PYTHONUSERBASE=/usr/local/
ENV PATH=${PYTHONUSERBASE}lib/python3.5/site-packages/bin:${PATH}
ENV PYTHONUNBUFFERED=0
